# Explore soft verification datasets

## 1. Transcriptformer
 - **1.1 TF: PMIs - Gene Pointwise Mutual Information Scores**
 - **1.2 TF: Gene Regulatory Networks - Transcription Factors 2 Transcription Factores Prediction**
 - **1.3 TF: Marker Genes 2 Transcription Factors Prediction**

In [1]:
import pandas as pd
import ast

TF_DATA_DIR = '/mnt/czi-sci-ai/project-rbio-40t/datasets/'

## 1.1 TF: PMIs - Gene Pointwise Mutual Information Scores

**1. Binary confidence scores** <br>
**2. Soft confidence scores**

In [2]:
tf_pmi_binary_df = pd.read_csv(f'{TF_DATA_DIR}TF_PMIs_sig_0.01-train-v0.0.3_binary.csv')
tf_pmi_soft_df = pd.read_csv(f'{TF_DATA_DIR}TF_PMIs_sig_0.01-train-v0.0.3_soft.csv')

get_confs_as_floats = lambda x: [eval(y) for y in x.split('|')]

tf_pmi_binary_df['class_confs_float'] = tf_pmi_binary_df['class_confidences'].apply(get_confs_as_floats)
tf_pmi_soft_df['class_confs_float'] = tf_pmi_soft_df['class_confidences'].apply(get_confs_as_floats)

In [3]:
tf_pmi_binary_df.head(2)

,gene_perturbed,gene_monitored,user_prompt,label,classes,keywords,system_prompt,cell_line,dataset_name,task,class_confidences,class_confs_float
0,ENSG00000284554,ENSG00000285932,Are gene ENSG00000284554 and gene ENSG00000285...,1,yes|no,ENSG00000284554|ENSG00000285932,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"
1,RIMBP3B,ENSG00000273520,Are gene RIMBP3B and gene ENSG00000273520 like...,1,yes|no,RIMBP3B|ENSG00000273520,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"

In [4]:
tf_pmi_soft_df.head(2)

,gene_perturbed,gene_monitored,user_prompt,label,classes,keywords,system_prompt,cell_line,dataset_name,task,class_confidences,class_confs_float
0,ENSG00000284554,ENSG00000285932,Are gene ENSG00000284554 and gene ENSG00000285...,1,yes|no,ENSG00000284554|ENSG00000285932,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,1.0|0.0,"[1.0, 0.0]"
1,RIMBP3B,ENSG00000273520,Are gene RIMBP3B and gene ENSG00000273520 like...,1,yes|no,RIMBP3B|ENSG00000273520,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,0.979296|0.0,"[0.979296, 0.0]"

In [5]:
tf_pmi_binary_df.groupby('label').count()

,gene_perturbed,gene_monitored,user_prompt,classes,keywords,system_prompt,cell_line,dataset_name,task,class_confidences,class_confs_float
label,,,,,,,,,,,
0,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997
1,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997

In [6]:
tf_pmi_soft_df.groupby('label').count()

,gene_perturbed,gene_monitored,user_prompt,classes,keywords,system_prompt,cell_line,dataset_name,task,class_confidences,class_confs_float
label,,,,,,,,,,,
0,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997
1,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997,2027997

In [7]:
def get_class_confidences_interval(df):
    all_class_confidences = set([])
    class_confidences = df['class_confs_float'].to_list()
    for cc in class_confidences:
        valid_confs = set([x for x in cc if x!=0])
        all_class_confidences.update(valid_confs)
    min_conf = min(all_class_confidences)
    max_conf = max(all_class_confidences)
    print(f'Min class confidence: {min_conf} | Max class confidence: {max_conf}')

In [8]:
get_class_confidences_interval(tf_pmi_binary_df)

Min class confidence: 1 | Max class confidence: 1

In [9]:
get_class_confidences_interval(tf_pmi_soft_df)

Min class confidence: 0.31312415 | Max class confidence: 1.0

## 1.2 TF: Gene Regulatory Networks - Transcription Factors 2 Transcription Factores Prediction**

**1. Binary confidence scores** <br>
**2. Soft confidence scores**

In [10]:
tf_gene_reg_binary_df = pd.read_csv(f'{TF_DATA_DIR}TF_TFs2genes_p_0.05-train-v0.0.3_binary.csv')
tf_gene_reg_soft_df = pd.read_csv(f'{TF_DATA_DIR}TF_TFs2genes_p_0.05-train-v0.0.3_soft.csv')

tf_gene_reg_binary_df['class_confs_float'] = tf_gene_reg_binary_df['class_confidences'].apply(get_confs_as_floats)
tf_gene_reg_soft_df['class_confs_float'] = tf_gene_reg_soft_df['class_confidences'].apply(get_confs_as_floats)

In [11]:
tf_gene_reg_binary_df.head(3)

,transcription_factor,gene_monitored,label,user_prompt,classes,keywords,system_prompt,cell_line,dataset_name,task,class_confidences,class_confs_float
0,ADNP,RABGAP1,1,"If transcription factor ADNP is activated, is ...",yes|no,ADNP|RABGAP1,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"
1,ADNP,TTC27,1,"If transcription factor ADNP is activated, is ...",yes|no,ADNP|TTC27,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"
2,ADNP,SPAST,1,"If transcription factor ADNP is activated, is ...",yes|no,ADNP|SPAST,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"

In [12]:
tf_gene_reg_soft_df.head(3)

,transcription_factor,gene_monitored,label,user_prompt,classes,keywords,system_prompt,cell_line,dataset_name,task,class_confidences,class_confs_float
0,ADNP,RABGAP1,1,"If transcription factor ADNP is activated, is ...",yes|no,ADNP|RABGAP1,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,0.023265794312575094|0.0,"[0.023265794312575094, 0.0]"
1,ADNP,TTC27,1,"If transcription factor ADNP is activated, is ...",yes|no,ADNP|TTC27,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,0.025797812466002514|0.0,"[0.025797812466002514, 0.0]"
2,ADNP,SPAST,1,"If transcription factor ADNP is activated, is ...",yes|no,ADNP|SPAST,A conversation between User and Biologist. The...,tf_3,TF_predictions,soft_verification,0.04717228169487444|0.0,"[0.04717228169487444, 0.0]"

In [13]:
get_class_confidences_interval(tf_gene_reg_binary_df)

Min class confidence: 1 | Max class confidence: 1

In [14]:
get_class_confidences_interval(tf_gene_reg_soft_df)

Min class confidence: 6.110420685132304e-29 | Max class confidence: 0.9999809061030311

## 1.3 TF: Marker Genes 2 Transcription Factors Prediction**

**1. Binary confidence scores** <br>
**2. Soft confidence scores**

In [15]:
tf_mg2tfs_binary_df = pd.read_csv(f'{TF_DATA_DIR}TF_MGs2TFs_pmi_0.8254-train-v0.0.3_binary.csv')
tf_mg2tfs_soft_df = pd.read_csv(f'{TF_DATA_DIR}TF_MGs2TFs_pmi_0.8254-train-v0.0.3_soft.csv')

tf_mg2tfs_binary_df['class_confs_float'] = tf_mg2tfs_binary_df['class_confidences'].apply(get_confs_as_floats)
tf_mg2tfs_soft_df['class_confs_float'] = tf_mg2tfs_soft_df['class_confidences'].apply(get_confs_as_floats)

In [16]:
tf_mg2tfs_binary_df.head()

,cell_type,gene_monitored,label,user_prompt,system_prompt,classes,keywords,cell_line,dataset_name,task,class_confidences,class_confs_float
0,cardiac endothelial cell,ZBTB16,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,ZBTB16,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"
1,cardiac endothelial cell,IRF1,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,IRF1,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"
2,cardiac endothelial cell,TSC22D1,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,TSC22D1,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"
3,cardiac endothelial cell,FOXP1,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,FOXP1,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"
4,cardiac endothelial cell,FOSB,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,FOSB,tf_3,TF_predictions,soft_verification,1|0,"[1, 0]"

In [17]:
tf_mg2tfs_soft_df.head()

,cell_type,gene_monitored,label,user_prompt,system_prompt,classes,keywords,cell_line,dataset_name,task,class_confidences,class_confs_float
0,cardiac endothelial cell,ZBTB16,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,ZBTB16,tf_3,TF_predictions,soft_verification,1.0|0.0,"[1.0, 0.0]"
1,cardiac endothelial cell,IRF1,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,IRF1,tf_3,TF_predictions,soft_verification,1.0|0.0,"[1.0, 0.0]"
2,cardiac endothelial cell,TSC22D1,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,TSC22D1,tf_3,TF_predictions,soft_verification,0.9074044006204858|0.0,"[0.9074044006204858, 0.0]"
3,cardiac endothelial cell,FOXP1,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,FOXP1,tf_3,TF_predictions,soft_verification,1.0|0.0,"[1.0, 0.0]"
4,cardiac endothelial cell,FOSB,1,"In a cell that has marker genes LDB2, EMCN, VW...",A conversation between User and Biologist. The...,yes|no,FOSB,tf_3,TF_predictions,soft_verification,0.9661063248740615|0.0,"[0.9661063248740615, 0.0]"

In [18]:
get_class_confidences_interval(tf_mg2tfs_binary_df)

Min class confidence: 1 | Max class confidence: 1

In [19]:
get_class_confidences_interval(tf_mg2tfs_soft_df)

Min class confidence: 0.00027831893132476503 | Max class confidence: 1.0